/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package basketstats;

/**
 *
 * @author capna
 */
public class TabelaPerfilAtleta extends javax.swing.JFrame {

    /**
     * Creates new form TabelaPerfilAtleta
     */
    public TabelaPerfilAtleta() {
        initComponents();
        javax.swing.table.DefaultTableModel modelo = 
        (javax.swing.table.DefaultTableModel) tabelaperfil.getModel(); 
    
    modelo.setRowCount(0);
    
    if (BasketStats.atletaLogado != null) {
        Atletas a = BasketStats.atletaLogado;
        
        modelo.addRow(new Object[]{
            a.getId(),
            a.getNome(),
            a.getIdade(),
            a.getPeso(),
            a.getAltura(),
            a.getPosicao(),
            a.getPontos(),
            a.getRebotes(),
            a.getAssist(),
            a.getTelefone(),
            a.getTime(),
            a.getCamp_atual()
    });
}

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaperfil = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btneditar = new javax.swing.JButton();
        btnvoltar = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaperfil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Idade", "Peso", "Altura", "Posição", "PPJ", "Rebotes", "Assist.", "Telefone", "Time", "Campeonato"
            }
        ));
        jScrollPane1.setViewportView(tabelaperfil);

        jScrollPane2.setViewportView(jScrollPane1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("MEU PERFIL ");

        btneditar.setText("EDITAR");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btnvoltar.setText("VOLTAR");
        btnvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarActionPerformed(evt);
            }
        });

        btnsalvar.setText("SALVAR");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnvoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btneditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnsalvar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btneditar)
                    .addComponent(btnvoltar)
                    .addComponent(btnsalvar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarActionPerformed
       TelaPrincipalAtleta tela = new TelaPrincipalAtleta();
       tela.setVisible(true);
       this.dispose(); 
    }//GEN-LAST:event_btnvoltarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
   tabelaperfil.setEnabled(true);

javax.swing.JOptionPane.showMessageDialog(
    this,
    "Agora você pode editar seus dados na tabela."
);
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
   if (tabelaperfil.isEditing()) {
        tabelaperfil.getCellEditor().stopCellEditing();
    }

    Atletas atleta = BasketStats.atletaLogado;

    if (atleta != null) {
        try {
            atleta.setNome(tabelaperfil.getValueAt(0, 1).toString());
            atleta.setIdade(Integer.parseInt(tabelaperfil.getValueAt(0, 2).toString()));
            atleta.setPeso(Double.parseDouble(tabelaperfil.getValueAt(0, 3).toString()));
            atleta.setAltura(Double.parseDouble(tabelaperfil.getValueAt(0, 4).toString()));
            atleta.setPosicao(tabelaperfil.getValueAt(0, 5).toString());
            atleta.setPontos(Double.parseDouble(tabelaperfil.getValueAt(0, 6).toString()));
            atleta.setRebotes(Double.parseDouble(tabelaperfil.getValueAt(0, 7).toString()));
            atleta.setAssist(Double.parseDouble(tabelaperfil.getValueAt(0, 8).toString()));
            atleta.setTelefone(tabelaperfil.getValueAt(0, 9).toString());
            atleta.setTime(tabelaperfil.getValueAt(0, 10).toString());
            atleta.setCamp_atual(tabelaperfil.getValueAt(0, 11).toString());

            System.out.println("Alterações feitas com sucesso no atleta: " + atleta.getNome());
            
            javax.swing.JOptionPane.showMessageDialog(this,
                "Alterações salvas com sucesso!"
            );
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Erro ao salvar! Certifique-se de digitar os números corretamente (use ponto '.' em vez de vírgula ',')."
            );
        }
    }
    }//GEN-LAST:event_btnsalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaPerfilAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaPerfilAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaPerfilAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaPerfilAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaPerfilAtleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JButton btnvoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaperfil;
    // End of variables declaration//GEN-END:variables
}
